// swift-tools-version: 5.9
//
// Prebuilt DoopEditor v0.11.0.
//
// Generated by Scripts/generate-binary-manifest.swift in matiaskorhonen/doop-editor -- do not edit by hand.
// The XCFramework is attached to the matching release there.
//
// `.binaryTarget` cannot declare dependencies, so the product lists every framework it
// needs transitively -- which is normally just itself, unless a dependency stopped being absorbed.
import PackageDescription

let package = Package(
    name: "DoopEditor",
    platforms: [.macOS(.v13)],
    products: [
        .library(
            name: "DoopEditor",
            targets: [
                "DoopEditor",
            ]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "DoopEditor",
            url: "https://github.com/matiaskorhonen/doop-editor/releases/download/v0.11.0/DoopEditor.xcframework.zip",
            checksum: "7f9c7bba57c7e02a6fb731d31e384195376d46f75fd61521723d82a833ef6b77"
        ),
    ]
)
