// swift-tools-version: 5.9
//
// Prebuilt DoopEditor v0.10.1.
//
// Generated by Scripts/generate-binary-manifest.swift in matiaskorhonen/doop-editor -- do not edit by hand.
// The XCFramework is attached to the matching release there.
//
// `.binaryTarget` cannot declare dependencies, so the product lists every framework it
// needs transitively -- which is normally just itself, unless a dependency stopped being absorbed.
import PackageDescription

let package = Package(
    name: "DoopEditor",
    platforms: [.macOS(.v13)],
    products: [
        .library(
            name: "DoopEditor",
            targets: [
                "DoopEditor",
            ]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "DoopEditor",
            url: "https://github.com/matiaskorhonen/doop-editor/releases/download/v0.10.1/DoopEditor.xcframework.zip",
            checksum: "5f0a88c1c158230c18adba20d02d7bee71ad7978542e56d76e25d664960527ec"
        ),
    ]
)
