// swift-tools-version: 5.9
//
// Prebuilt DoopEditor v0.10.0.
//
// Generated by Scripts/generate-binary-manifest.swift in matiaskorhonen/doop-editor -- do not edit by hand.
// The XCFramework is attached to the matching release there.
//
// `.binaryTarget` cannot declare dependencies, so the product lists every framework it
// needs transitively -- which is normally just itself, unless a dependency stopped being absorbed.
import PackageDescription

let package = Package(
    name: "DoopEditor",
    platforms: [.macOS(.v13)],
    products: [
        .library(
            name: "DoopEditor",
            targets: [
                "DoopEditor",
            ]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "DoopEditor",
            url: "https://github.com/matiaskorhonen/doop-editor/releases/download/v0.10.0/DoopEditor.xcframework.zip",
            checksum: "94d3bad40b2ebfaee591dfa309b9262d9b9fec8ee2d146d6c7ebe861e22ea4ee"
        ),
    ]
)
